<?php

return [
    'items' => [
        [
            'label' => 'Dashboard',
            'icon' => 'bx bx-home-alt-2',
            'route' => 'dashboard',
            'active' => ['dashboard', 'dashboard.*'],
            'enabled' => true,
        ],
        [
            'label' => 'Empresas',
            'icon' => 'bx bx-buildings',
            'enabled' => true,
            'active' => ['companies.*'],
            'can' => 'viewAny',
            'model' => \App\Models\Company::class,
            'children' => [
                [
                    'label' => 'Listado',
                    'icon' => 'bx bx-list-ul',
                    'route' => 'companies.index',
                    'active' => ['companies.index'],
                    'enabled' => true,
                    'can' => 'viewAny',
                    'model' => \App\Models\Company::class,
                ],
                [
                    'label' => 'Registrar',
                    'icon' => 'bx bx-plus-circle',
                    'route' => 'companies.create',
                    'active' => ['companies.create'],
                    'enabled' => true,
                    'can' => 'create',
                    'model' => \App\Models\Company::class,
                ],
            ],
        ],
        [
            'label' => 'Usuarios',
            'icon' => 'bx bx-group',
            'enabled' => true,
            'active' => ['users.*'],
            'can' => 'viewAny',
            'model' => \App\Models\User::class, 
            'children' => [
                [
                    'label' => 'Listado',
                    'icon' => 'bx bx-list-ol',
                    'route' => 'users.index',
                    'active' => ['users.index'],
                    'enabled' => true,
                    'can' => 'viewAny',
                    'model' => \App\Models\User::class,
                ],
                [
                    'label' => 'Invitar Usuario',
                    'icon' => 'bx bx-user-plus',
                    'route' => 'users.create',
                    'active' => ['users.create'],
                    'enabled' => true,
                    'can' => 'create',
                    'model' => \App\Models\User::class,
                ],
            ],
        ],
        [
            'label' => 'Reportes',
            'icon' => 'bx bx-file',
            'enabled' => true,
            'active' => ['reports.*'],
            'can' => 'viewAny',
            'model' => \App\Models\Report::class,
            'children' => [
                [
                    'label' => 'Todos',
                    'icon' => 'bx bx-list-ul',
                    'route' => 'reports.index',
                    'active' => ['reports.index'],
                    'enabled' => true,
                    'can' => 'viewAny',
                    'model' => \App\Models\Report::class,
                ],
                [
                    'label' => 'Subir Reporte',
                    'icon' => 'bx bx-cloud-upload',
                    'route' => 'reports.create',
                    'active' => ['reports.create'],
                    'enabled' => true,
                    'can' => 'create',
                    'model' => \App\Models\Report::class,
                ],
            ],
        ],
        [
            'label' => 'Obligaciones',
            'icon' => 'bx bx-task',
            'enabled' => true,
            'active' => ['menu.obligaciones.*', 'obligations.*', 'credentials.*'],
            'can' => 'viewAny',
            'model' => \App\Models\Obligation::class,
            'children' => [
                [
                    'label' => 'Calendario',
                    'icon' => 'bx bx-calendar',
                    'route' => 'menu.obligaciones.calendario',
                    'active' => ['menu.obligaciones.calendario', 'obligations.*'],
                    'enabled' => true,
                    'can' => 'viewAny',
                    'model' => \App\Models\Obligation::class,
                ],
                [
                    'label' => 'Instancias',
                    'icon' => 'bx bx-check-shield',
                    'route' => 'menu.obligaciones.instancias',
                    'active' => ['menu.obligaciones.instancias', 'credentials.*'],
                    'enabled' => true,
                    'can' => 'viewAny',
                    'model' => \App\Models\Credential::class,
                ],
            ],
        ],
        [
            'label' => 'Noticias',
            'icon' => 'bx bx-news',
            'route' => 'news.index',
            'active' => ['news.*'],
            'enabled' => true,
            'can' => 'viewAny',
            'model' => \App\Models\News::class,
        ],
        [
            'label' => 'Tutoriales',
            'icon' => 'bx bx-video',
            'route' => 'tutorials.index',
            'active' => ['tutorials.*'],
            'enabled' => true,
            'can' => 'viewAny',
            'model' => \App\Models\Tutorial::class,
        ],
        [
            'label' => 'Documentos Finales',
            'icon' => 'bx bx-folder',
            'route' => 'final-documents.index',
            'active' => ['final-documents.*'],
            'enabled' => true,
            'can' => 'viewAny',
            'model' => \App\Models\FinalDocument::class,
        ],
        [
            'label' => 'Bandeja de Entrada',
            'icon' => 'bx bx-message-square-detail',
            'route' => 'tickets.index',
            'active' => ['tickets.*'],
            'enabled' => true,
            'can' => 'viewAny',
            'model' => \App\Models\Ticket::class,
        ],
        [
            'label' => 'Facturador',
            'icon' => 'bx bx-receipt',
            'enabled' => true,
            'active' => ['facturador.*'],
            'can' => 'viewAny',
            'model' => \App\Models\Invoice::class,
            'children' => [
                [
                    'label' => 'Mis Empresas',
                    'icon' => 'bx bx-building',
                    'route' => 'facturador.index',
                    'active' => ['facturador.index'],
                    'enabled' => true,
                    'can' => 'viewAny',
                    'model' => \App\Models\Invoice::class,
                ],
                [
                    'label' => 'Productos',
                    'icon' => 'bx bx-box',
                    'route' => 'facturador.products.index',
                    'active' => ['facturador.products.*'],
                    'enabled' => true,
                    'can' => 'viewAny',
                    'model' => \App\Models\Product::class,
                ],
                [
                    'label' => 'Clientes',
                    'icon' => 'bx bx-user',
                    'route' => 'facturador.clients.index',
                    'active' => ['facturador.clients.*'],
                    'enabled' => true,
                    'can' => 'viewAny',
                    'model' => \App\Models\Client::class,
                ],
                [
                    'label' => 'Comprobantes',
                    'icon' => 'bx bx-file',
                    'route' => 'facturador.invoices.index',
                    'active' => ['facturador.invoices.*'],
                    'enabled' => true,
                    'can' => 'viewAny',
                    'model' => \App\Models\Invoice::class,
                ],
                [
                    'label' => 'Config. Feasy',
                    'icon' => 'bx bx-key',
                    'route' => 'configuracion.feasy.edit',
                    'active' => ['configuracion.feasy.*'],
                    'enabled' => true,
                    'can' => 'updateFacturadorConfig',
                    'model' => \App\Models\Company::class,
                ],
            ],
        ],
        [
            'label' => 'Portal SUNAT',
            'icon' => 'bx bx-shield-quarter',
            'route' => 'portal-sunat.index',
            'active' => ['portal-sunat.*'],
            'enabled' => true,
            'can' => 'viewAny',
            'model' => \App\Models\Company::class,
        ],
        [
            'label'   => 'Configuración',
            'icon'    => 'bx bx-cog',
            'active'  => ['menu.configuracion', 'admin.audit-log.*', 'configuracion.*'],
            'enabled' => true,
            'can'     => 'manageCompanies',
            'model'   => \App\Models\Company::class,
            'children' => [
                [
                    'label'   => 'Auditoría del Sistema',
                    'icon'    => 'bx bx-history',
                    'route'   => 'admin.audit-log.index',
                    'active'  => ['admin.audit-log.*'],
                    'enabled' => true,
                    'can'     => 'manageCompanies',
                    'model'   => \App\Models\Company::class,
                ],
                [
                    'label'   => 'Config. Feasy',
                    'icon'    => 'bx bx-wrench',
                    'route'   => 'configuracion.feasy.edit',
                    'active'  => ['configuracion.feasy.*'],
                    'enabled' => true,
                    'can'     => 'updateFacturadorConfig',
                    'model'   => \App\Models\Company::class,
                ],
            ],
        ],
    ],
];
