<?php

return [
    'items' => [
        [
            'label' => 'Dashboard',
            'icon' => 'bx bx-home-alt-2',
            'route' => 'dashboard',
            'active' => ['dashboard', 'dashboard.*'],
            'enabled' => true,
        ],
        [
            'label' => 'Empresas',
            'icon' => 'bx bx-buildings',
            'enabled' => true,
            'active' => ['companies.*'],
            'can' => 'viewAny',
            'model' => \App\Models\Company::class,
            'children' => [
                [
                    'label' => 'Listado',
                    'icon' => 'bx bx-list-ul',
                    'route' => 'companies.index',
                    'active' => ['companies.index'],
                    'enabled' => true,
                    'can' => 'viewAny',
                    'model' => \App\Models\Company::class,
                ],
                [
                    'label' => 'Registrar',
                    'icon' => 'bx bx-plus-circle',
                    'route' => 'companies.create',
                    'active' => ['companies.create'],
                    'enabled' => true,
                    'can' => 'create',
                    'model' => \App\Models\Company::class,
                ],
            ],
        ],
        [
            'label' => 'Usuarios',
            'icon' => 'bx bx-group',
            'enabled' => true,
            'active' => ['users.*'],
            'can' => 'viewAny',
            'model' => \App\Models\User::class, 
            'children' => [
                [
                    'label' => 'Listado',
                    'icon' => 'bx bx-list-ol',
                    'route' => 'users.index',
                    'active' => ['users.index'],
                    'enabled' => true,
                    'can' => 'viewAny',
                    'model' => \App\Models\User::class,
                ],
                [
                    'label' => 'Invitar Usuario',
                    'icon' => 'bx bx-user-plus',
                    'route' => 'users.create',
                    'active' => ['users.create'],
                    'enabled' => true,
                    'can' => 'create',
                    'model' => \App\Models\User::class,
                ],
            ],
        ],
        [
            'label' => 'Reportes',
            'icon' => 'bx bx-file',
            'enabled' => true,
            'active' => ['reports.*'],
            'can' => 'viewAny',
            'model' => \App\Models\Report::class,
            'children' => [
                [
                    'label' => 'Todos',
                    'icon' => 'bx bx-list-ul',
                    'route' => 'reports.index',
                    'active' => ['reports.index'],
                    'enabled' => true,
                    'can' => 'viewAny',
                    'model' => \App\Models\Report::class,
                ],
                [
                    'label' => 'Subir Reporte',
                    'icon' => 'bx bx-cloud-upload',
                    'route' => 'reports.create',
                    'active' => ['reports.create'],
                    'enabled' => true,
                    'can' => 'create',
                    'model' => \App\Models\Report::class,
                ],
            ],
        ],
        [
            'label' => 'Obligaciones',
            'icon' => 'bx bx-task',
            'enabled' => true,
            'active' => ['menu.obligaciones.*', 'obligations.*'],
            'can' => 'viewAny',
            'model' => \App\Models\Obligation::class,
            'children' => [
                [
                    'label' => 'Instancias',
                    'icon' => 'bx bx-check-shield',
                    'route' => 'menu.obligaciones.instancias',
                    'active' => ['menu.obligaciones.instancias'],
                    'enabled' => false,
                    'can' => 'viewAny',
                    'model' => \App\Models\Credential::class,
                ],
                [
                    'label' => 'Cronograma de Obligaciones Mensuales',
                    'icon' => 'bx bx-calendar-check',
                    'route' => 'obligaciones.cronograma.index',
                    'active' => ['obligaciones.cronograma.*'],
                    'enabled' => true,
                    'exclude_roles' => ['client'],
                    'can' => 'viewAny',
                    'model' => \App\Models\Obligation::class,
                ],
            ],
        ],
        [
            'label' => 'Noticias',
            'icon' => 'bx bx-news',
            'route' => 'news.index',
            'active' => ['news.*'],
            'enabled' => true,
            'can' => 'viewAny',
            'model' => \App\Models\News::class,
        ],
        [
            'label' => 'Tutoriales',
            'icon' => 'bx bx-video',
            'route' => 'tutorials.index',
            'active' => ['tutorials.*'],
            'enabled' => true,
            'can' => 'viewAny',
            'model' => \App\Models\Tutorial::class,
        ],
        [
            'label' => 'Documentos Finales',
            'icon' => 'bx bx-folder',
            'route' => 'final-documents.index',
            'active' => ['final-documents.*'],
            'enabled' => true,
            'can' => 'viewAny',
            'model' => \App\Models\FinalDocument::class,
        ],
        [
            'label' => 'Bandeja de Entrada',
            'icon' => 'bx bx-message-square-detail',
            'route' => 'tickets.index',
            'active' => ['tickets.*'],
            'enabled' => true,
            'can' => 'viewAny',
            'model' => \App\Models\Ticket::class,
        ],
        [
            'label' => 'Facturador',
            'icon' => 'bx bx-receipt',
            'enabled' => true,
            'active' => ['facturador.*'],
            'can' => 'viewAny',
            'model' => \App\Models\Invoice::class,
            'children' => [
                ['type' => 'section', 'label' => 'Operación', 'enabled' => true],
                [
                    'label' => 'Comprobantes',
                    'icon' => 'bx bx-file',
                    'route' => 'facturador.invoices.index',
                    'active' => ['facturador.invoices.*'],
                    'enabled' => true,
                    'can' => 'viewAny',
                    'model' => \App\Models\Invoice::class,
                ],
                [
                    'label' => 'Compras',
                    'icon' => 'bx bx-cart',
                    'route' => 'facturador.compras.index',
                    'active' => ['facturador.compras.*'],
                    'enabled' => true,
                    'can' => 'viewAny',
                    'model' => \App\Models\Invoice::class,
                ],
                [
                    'label' => 'Subir compra',
                    'icon' => 'bx bx-cloud-upload',
                    'route' => 'facturador.compras.subir',
                    'active' => ['facturador.compras.subir*'],
                    'enabled' => true,
                    'can' => 'create',
                    'model' => \App\Models\Purchase::class,
                ],
                [
                    'label' => 'Guías de remisión',
                    'icon' => 'bx bx-map-alt',
                    'route' => 'facturador.gre.index',
                    'active' => ['facturador.gre.*'],
                    'enabled' => true,
                    'can' => 'viewAny',
                    'model' => \App\Models\Invoice::class,
                ],
                ['type' => 'section', 'label' => 'Catálogos', 'enabled' => true],
                [
                    'label' => 'Clientes',
                    'icon' => 'bx bx-user',
                    'route' => 'facturador.clients.index',
                    'active' => ['facturador.clients.*'],
                    'enabled' => true,
                    'can' => 'viewAny',
                    'model' => \App\Models\Client::class,
                ],
                [
                    'label' => 'Productos/Servicios',
                    'icon' => 'bx bx-box',
                    'route' => 'facturador.products.index',
                    'active' => ['facturador.products.*'],
                    'enabled' => true,
                    'can' => 'viewAny',
                    'model' => \App\Models\Product::class,
                ],
                ['type' => 'section', 'label' => 'Finanzas', 'enabled' => true],
                [
                    'label'   => 'Letras de Cambio',
                    'icon'    => 'bx bx-transfer',
                    'route'   => 'facturador.letras.index',
                    'active'  => ['facturador.letras.*'],
                    'enabled' => true,
                    'can'     => 'viewAny',
                    'model'   => \App\Models\Purchase::class,
                ],
                [
                    'label'      => 'Cotizaciones',
                    'icon'       => 'bx bx-table',
                    'route'      => 'facturador.cotizaciones.index',
                    'active'     => ['facturador.cotizaciones.*'],
                    'enabled'    => true,
                    'requires_quote_enabled' => true,
                    'can'        => 'viewAny',
                    'model'      => \App\Models\Invoice::class,
                ],
                [
                    'label'      => 'Cotizador rápido',
                    'icon'       => 'bx bx-receipt',
                    'route'      => 'facturador.quotations.create',
                    'active'     => ['facturador.quotations.*'],
                    'enabled'    => true,
                    'requires_quote_enabled' => true,
                    'can'        => 'viewAny',
                    'model'      => \App\Models\Invoice::class,
                ],
                ['type' => 'section', 'label' => 'Administración', 'enabled' => true],
                [
                    'label' => 'Mis Empresas',
                    'icon' => 'bx bx-building',
                    'route' => 'facturador.index',
                    'active' => ['facturador.index'],
                    'enabled' => true,
                    'can' => 'viewAny',
                    'model' => \App\Models\Invoice::class,
                ],
                [
                    'label' => 'Emitidos global',
                    'icon' => 'bx bx-spreadsheet',
                    'route' => 'facturador.admin-issued-invoices.index',
                    'active' => ['facturador.admin-issued-invoices.*'],
                    'enabled' => true,
                    'only_roles' => ['admin', 'supervisor'],
                ],
                [
                    'label' => 'Notas Crédito/Débito',
                    'icon' => 'bx bx-file-blank',
                    'route' => 'facturador.credit-debit-notes.index',
                    'active' => ['facturador.credit-debit-notes.*'],
                    'enabled' => false, // Oculto temporalmente
                    'can' => 'viewAny',
                    'model' => \App\Models\CreditDebitNote::class,
                ],
                [
                    'label'      => 'Config. Comprobante/Cotizador',
                    'icon'       => 'bx bx-palette',
                    'route'      => 'facturador.quote-settings.edit',
                    'active'     => ['facturador.quote-settings.*'],
                    'enabled'    => true,
                    'can'        => 'viewAny',
                    'model'      => \App\Models\Invoice::class,
                ],
                [
                    'label' => 'Config. Feasy',
                    'icon' => 'bx bx-key',
                    'route' => 'configuracion.feasy.edit',
                    'active' => ['configuracion.feasy.*'],
                    'enabled' => true,
                    'can' => 'updateFacturadorConfig',
                    'model' => \App\Models\Company::class,
                ],
            ],
        ],
        [
            'label'   => 'SUNAT',
            'icon'    => 'bx bx-shield-quarter',
            'enabled' => true,
            'active'  => ['portal-sunat.*', 'bandeja-sunat.*'],
            'can'     => 'viewAny',
            'model'   => \App\Models\Company::class,
            'children' => [
                [
                    'label'   => 'Portal SUNAT',
                    'icon'    => 'bx bx-monitor',
                    'route'   => 'portal-sunat.index',
                    'active'  => ['portal-sunat.*'],
                    'enabled' => true,
                    'can'     => 'viewAny',
                    'model'   => \App\Models\Company::class,
                ],
                [
                    'label'   => 'Buzón SOL',
                    'icon'    => 'bx bx-envelope',
                    'route'   => 'bandeja-sunat.index',
                    'active'  => ['bandeja-sunat.*'],
                    'enabled' => true,
                    'can'     => 'viewAny',
                    'model'   => \App\Models\Company::class,
                ],
                [
                    'label'   => 'Validar Comprobantes',
                    'icon'    => 'bx bx-check-shield',
                    'route'   => 'sunat.comprobantes.validar.index',
                    'active'  => ['sunat.comprobantes.*'],
                    'enabled' => true,
                    'can'     => 'viewAny',
                    'model'   => \App\Models\Company::class,
                ],
            ],
        ],
        [
            'label'   => 'Configuración',
            'icon'    => 'bx bx-cog',
            'active'  => ['menu.configuracion', 'admin.audit-log.*', 'configuracion.*'],
            'enabled' => true,
            'can'     => 'manageCompanies',
            'model'   => \App\Models\Company::class,
            'children' => [
                [
                    'label'   => 'Auditoría del Sistema',
                    'icon'    => 'bx bx-history',
                    'route'   => 'admin.audit-log.index',
                    'active'  => ['admin.audit-log.*'],
                    'enabled' => true,
                    'can'     => 'manageCompanies',
                    'model'   => \App\Models\Company::class,
                ],
                [
                    'label'   => 'Config. Feasy',
                    'icon'    => 'bx bx-wrench',
                    'route'   => 'configuracion.feasy.edit',
                    'active'  => ['configuracion.feasy.*'],
                    'enabled' => true,
                    'can'     => 'updateFacturadorConfig',
                    'model'   => \App\Models\Company::class,
                ],
            ],
        ],
        [
            'label'   => 'Links de interés',
            'icon'    => 'bx bx-link-external',
            'enabled' => true,
            'active'  => [],
            'children' => [
                ['type' => 'section', 'label' => 'TODO DE SUNAT', 'enabled' => true],
                ['label' => 'Mesa de Partes ',  'url' => 'https://ww1.sunat.gob.pe/ol-at-ittramitedoc/registro/iniciar',                                                                                                                                                                                'icon' => 'bx bx-send',         'target' => '_blank', 'enabled' => true, 'active' => []],
                ['label' => 'Cronograma 2026', 'url' => 'https://www.sunat.gob.pe/orientacion/cronogramas/2026/cObligacionMensual2026.html',                                                                                                                                                         'icon' => 'bx bx-calendar',     'target' => '_blank', 'enabled' => true, 'active' => []],
                ['label' => 'Consulta RUC',    'url' => 'https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/FrameCriterioBusquedaWeb.jsp',                                                                                                                                                         'icon' => 'bx bx-search',       'target' => '_blank', 'enabled' => true, 'active' => []],
                ['label' => 'Emitir RH',       'url' => 'https://ww1.sunat.gob.pe/xssecurity/SignOnVerification.htm?signonForwardAction=https%3A%2F%2Fww1.sunat.gob.pe%2Fol-ti-itrheemision%2Femisionrhe.do',                                                                                      'icon' => 'bx bx-file',         'target' => '_blank', 'enabled' => true, 'active' => []],
                ['label' => 'Nota crédito RH', 'url' => 'https://ww1.sunat.gob.pe/xssecurity/SignOnVerification.htm?signonForwardAction=https%3A%2F%2Fww1.sunat.gob.pe%2Fol-ti-itrheemisionnce%2Femisionnce.do',                                                                                   'icon' => 'bx bx-file-blank',   'target' => '_blank', 'enabled' => true, 'active' => []],
                ['label' => 'Validar CPE',          'url' => 'https://e-consulta.sunat.gob.pe/ol-ti-itconsvalicpe/ConsValiCpe.htm',                                                                                                                                                                                                              'icon' => 'bx bx-check-shield',  'target' => '_blank', 'enabled' => true, 'active' => []],
                ['label' => 'Tipo de Cambio SUNAT',  'url' => 'https://e-consulta.sunat.gob.pe/cl-at-ittipcam/tcS01Alias',                                                                                                                                                                                                                    'icon' => 'bx bx-dollar-circle', 'target' => '_blank', 'enabled' => true, 'active' => []],
                ['label' => 'Renta Anual Personas 709', 'url' => 'https://api-seguridad.sunat.gob.pe/v1/clientessol/03590141-c69c-438c-a36a-8ee2a3ad9747/oauth2/login?originalUrl=https://e-renta.sunat.gob.pe/loader/recaudaciontributaria/declaracionpago/formularios', 'icon' => 'bx bx-user-circle',    'target' => '_blank', 'enabled' => true, 'active' => []],
                ['label' => 'Renta Anual Empresas 710', 'url' => 'https://api-seguridad.sunat.gob.pe/v1/clientessol/03590141-c69c-438c-a36a-8ee2a3ad9747/oauth2/login?originalUrl=https://e-renta.sunat.gob.pe/loader/recaudaciontributaria/declaracionpago/formularios', 'icon' => 'bx bx-buildings',      'target' => '_blank', 'enabled' => true, 'active' => []],
                ['label' => 'Cronograma L.E(Libros Electronicos)',        'url' => 'https://www.sunat.gob.pe/orientacion/cronogramas/cronoRegistroC-V-2026.html',                                                                                                                                                                                                  'icon' => 'bx bx-book-open',     'target' => '_blank', 'enabled' => true, 'active' => []],
                ['label' => 'Cronograma Renta Anual 2025','url' => 'https://www.sunat.gob.pe/orientacion/cronogramas/2026/cRenta2025.html',                                                                                                                                                                                                        'icon' => 'bx bx-calendar-event','target' => '_blank', 'enabled' => true, 'active' => []],
                ['type' => 'section', 'label' => 'Otros', 'enabled' => true],
                ['label' => 'Mesa de Partes SUNAFIL',    'url' => 'https://aplicativosweb6.sunafil.gob.pe/si.mesaVirtual/registro', 'icon' => 'bx bx-inbox',     'target' => '_blank', 'enabled' => true, 'active' => []],
                ['label' => 'Tribunal Fiscal', 'url' => 'https://tribunalfiscal.pegasus.com.pe/',                         'icon' => 'bx bx-buildings', 'target' => '_blank', 'enabled' => true, 'active' => []],
            ],
        ],
    ],
];
